### ISSUE TITLE
A little question towards running the augmentation part for this code

### ISSUE THREAD

**Issue by Zhaoyi-Li21** [tanyuqian/learning-data-manipulation#11]
Hello, there
Thanks a lot for your opening source your code and your impressive work.
I met up with a little problem when I was trying to reproduce the data augmentation part for text in scripts folder providered by you. (specifically, say, I want to run the script : run_augmentation_sst5_low.sh)
It seems that you set the data augmentation experience running on a single GPU So I just run your code without changing anything on a RTX2080 GPU(around 10GiB storage space available) and here is a 'CUDA out of memory' error occurring when I finished the phases of 'Classifier Pre-training' and 'Generator Pre-training' and just started the phase of 'Training'.

Could you plz imform me of the rough memory requirement of gpu towards running this part? And whether you were making use of multi-gpus to run this part or not? (I noticed that you metioned that '4*RTX1080Ti GPUs and 64GBRAM' in your paper, does 'RAM' here mean storage of GPU?)

I'd appreciate it if receiving a reply!

**Comment by tanyuqian** [comment]
Thanks for noticing our work! We don't use multi-gpus on any single experiment. Every script of our experiments runs on a single 1080Ti GPU with 11GB GPU memory. (so I guess the 8GB memory of 2080 GPU could be not enough.) "64GB RAM" is the RAM of the server instead of the GPUs.

**Comment by Zhaoyi-Li21** [comment]
thanks a lot for your reply :)
btw I actually used RTX2080Ti GPU which also has 11GB memory and it seems that it still cause OOM error while running for exps and I finally used Tesla 100 successfully running for exps and reproducing for results.
thanks for your reply and impressive reproduciable work again anyway.
