### ISSUE TITLE
question about data_seed

### ISSUE THREAD

**Issue by RenShuhuai-Andy** [tanyuqian/learning-data-manipulation#4]
Hi !
The loop in `run_augmentation_sst5_low.sh`
https://github.com/tanyuqian/learning-data-manipulation/blob/master/scripts/run_augmentation_sst5_low.sh#L1-L14
keeps args.data_seed=159, which means the train/valid/test examples are all the same during this loop, right? I want to know whether the mean/variance of the results reported in your paper is only for model training, not data under different random seeds?

**Comment by tanyuqian** [comment]
Right, all runs use one same set of train/dev/test examples. We use a set of train/dev/test examples and collect mean/variance from multiple runs with different random seeds of model training, like what every typical ML task does.

We did try setting other data_seeds without tuning other hyperparameters. As you can imagine, the result numbers with different data_seeds vary a lot, but the improvement of our methods is consistent.

Results of "sst-5 low data" with data_seed=11111 are shown below (simply add ```--data_seed 11111``` to the command):

Baseline: ```36.24 +- 5.48```
Ren et al.: ```35.94 +- 3.35```
Weighting: ```39.47 +- 3.76```
Augmentation: ```40.13 +- 2.86```

**Comment by RenShuhuai-Andy** [comment]
Thanks a lot
