### ISSUE TITLE
code quesiton

### ISSUE THREAD

**Issue by luolanfeixue** [tanyuqian/learning-data-manipulation#5]
what the function do? why define a magic_model?
classifier.finetune_generator(example, aug_probs, finetune_batch_size=len(examples))

**Comment by tanyuqian** [comment]
[This reply](https://github.com/tanyuqian/learning-data-manipulation/issues/2#issuecomment-596288379) in a closed issue might be able to help you a bit. Please let me know if you are still confused about anywhere.
