### ISSUE TITLE
question about training speed based on a big validation set size 

### ISSUE THREAD

**Issue by lemon234071** [tanyuqian/learning-data-manipulation#8]
I want to know that the method update DM grad every batch by running on validation set once. If the size of validation set is big, the time cost so much, any method could deal with it?

Thank you very much

**Comment by lemon234071** [comment]
additonal question: "magic_model.update_params(deltas)" must update sample by sample? Is there any method to update batch by batch?

Thank you very much

**Comment by tanyuqian** [comment]
Re 1: I guess there are two possible ways you can try: (1) sample a subset from the validation set every time. (2) update the augmentation model periodically after multiple steps instead of every single step.

Re 2: Sure it can be batch-by-batch. It's just a designing choice related to coding, no conflict with the method of our paper.

**Comment by lemon234071** [comment]
> Re 1: I guess there are two possible ways you can try: (1) sample a subset from the validation set every time. (2) update the augmentation model periodically after multiple steps instead of every single step.
> 
> Re 2: Sure it can be batch-by-batch. It's just a designing choice related to coding, no conflict with the method of our paper.

Thank you very much!!!!

**Comment by lemon234071** [comment]
> Re 1: I guess there are two possible ways you can try: (1) sample a subset from the validation set every time. (2) update the augmentation model periodically after multiple steps instead of every single step.
> 
> Re 2: Sure it can be batch-by-batch. It's just a designing choice related to coding, no conflict with the method of our paper.

Can you give some idea to run it batch-by-batch? (the option bothers me , in "weighting/classifier.py" line 138:deltas = {name: weights[i] * delta.data for name, delta in deltas.items()})
